services:
  db:
    image: postgres:16
    container_name: twitter_db
    environment:
      POSTGRES_DB: twitter_clone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: twitter_redis
    ports:
      - "6379:6379"
